services:
  database:
    image: postgres:latest
    container_name: ${CONTAINER_NAME_POSTGRES}
    restart: always
    env_file: ./.env
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    networks:
      - ezt
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_POSTGRES_USER} -d ${DB_DATABASE_NAME}",
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: ghcr.io/eztest.ai-app:latest
    depends_on:
      database:
        condition: service_healthy
    container_name: ${CONTAINER_NAME_APP}
    ports:
      - "${PORT_APP}:3000"
    env_file: ./.env
    environment:
      NEXT_BASE_URL: ${DOMAIN_BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      AUTH_SECRET: ${AUTH_SECRET}
    restart: unless-stopped
    networks:
      - ezt

  migrator:
    image: ghcr.io/eztest.ai-migrator:latest
    depends_on:
      database:
        condition: service_healthy
    container_name: ${CONTAINER_NAME_MIGRATOR}
    env_file: ./.env
    networks:
      - ezt

networks:
  ezt:
    driver: bridge
