name: Deploy to DEV environment

on:
  push:
    branches:
      - develop

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT_TOKEN }}
          registry: ghcr.io

      - name: Build Docker image
        run: |
          docker build -f ./Dockerfile -t ghcr.io/${{ github.repository }}-app:latest . --no-cache
          docker build -f ./Dockerfile.db -t ghcr.io/${{ github.repository }}-migrator:latest . --no-cache

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}-app:latest
          docker push ghcr.io/${{ github.repository }}-migrator:latest

      - name: Delete older local images
        run: |
          app_images=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "ghcr.io/belsterns/eztest.ai-app" | grep -v ':latest' || true)
          migrator_images=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep "ghcr.io/belsterns/eztest.ai-migrator" | grep -v ':latest' || true)
          
          if [ -z "$app_images" ] && [ -z "$migrator_images" ]; then
            echo "No old images found to delete."
          else
            for image in $app_images $migrator_images; do
              echo "Removing old image $image"
              docker rmi "$image" || echo "Failed to remove image $image"
            done
          fi
          
          docker builder prune -f || echo "Failed to prune builder cache"


  pull-deploy:
    needs: build-push
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

      - name: Install gettext (for envsubst)
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext

      - name: Deploy to Server
        env:
          DEV_SERVER_IP: ${{ secrets.DEV_SERVER_IP }}
          DEV_PRJ_PATH: ${{ secrets.DEV_PRJ_PATH }}
        run: |
          scp -o StrictHostKeyChecking=no ./docker-compose.yaml apl_dev@${DEV_SERVER_IP}:${DEV_PRJ_PATH}/docker-compose.yml
          ssh -o LogLevel=verbose -o StrictHostKeyChecking=no root@${DEV_SERVER_IP} << EOF
          docker login --username ${{ github.actor }} --password ${{ secrets.CONTAINER_REGISTRY_PAT_TOKEN }} ghcr.io
          docker image pull ghcr.io/${{ github.repository }}-app:latest
          docker image pull ghcr.io/${{ github.repository }}-migrator:latest
          docker compose -f ${DEV_PRJ_PATH}/docker-compose.yml up -d --force-recreate
          docker image prune -f
          EOF
